# Generated by Django 4.2.5 on 2023-09-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='slug')),
                ('conteхt', models.TextField(verbose_name='Содержимое')),
                ('preview_img', models.ImageField(upload_to='blog/images/', verbose_name='Превью(изображение)')),
                ('date_create', models.DateField(default='18.09.2023', verbose_name='Дата создания')),
                ('sign_of_publication', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
        ),
    ]
