# Generated by Django 4.2.5 on 2023-09-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date_create_alter_blog_preview_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sign_of_publication',
            new_name='is_published',
        ),
    ]
