# Generated by Django 4.2.5 on 2023-10-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_sign_of_publication_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateField(default='2023-10-15', verbose_name='Дата создания'),
        ),
    ]
