# Generated by Django 4.2.5 on 2023-09-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_quantity_product_quantity_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateField(default='19.09.2023', verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_last_change',
            field=models.DateField(default='19.09.2023', verbose_name='дата последнего изменения'),
        ),
    ]
